---
- name: check that certificates are provided if https
  assert:
    that:
      - csrgen_cert is defined
      - csrgen_ca_cert is defined
      - csrgen_private_key is defined
  when: csrgen_https|bool

- name: create group
  group:
    name: "{{ csrgen_group }}"
    system: yes

- name: create user
  user:
    name: "{{ csrgen_user }}"
    home: "{{ csrgen_home }}"
    system: yes

- name: create extra directories
  file:
    path: "{{ csrgen_home }}/{{ item }}"
    state: directory
    owner: "{{ csrgen_user }}"
    group: "{{ csrgen_group }}"
  with_items:
    - archive
    - conf
    - logs
    - run

# TODO(dw): We can avoid pulling in EPEL if we get pip elsewhere
- name: install epel repo
  yum:
    name: epel-release
    state: present

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - openssl-devel
    - python-pip
    - python-devel
    - libsemanage-python

- name: set httpd_can_network_connect (selinux)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"
