galaxy_info:
  author: David Wittman
  description: Deploys csrgenerator.com
  license: BSD
  min_ansible_version: 2.0
  github_branch: master
  platforms:
   - name: EL
     versions:
      - 7
  galaxy_tags: []

dependencies: []
